name: Dagens Ordnet

on:
  workflow_call:
  workflow_dispatch:

jobs:
  dagens-ordnet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Dagens Ordnet repository
        uses: actions/checkout@v5
        with:
          repository: "${{ github.repository_owner }}/dagens-ordnet"
          path: "${{ github.workspace }}/"
          token: "${{ secrets.PAT }}"

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install -r ${{ github.workspace }}/requirements.txt

      - name: Run Dagens Ordnet script
        run: |
          python ${{ github.workspace }}/dagens_ordnet.py