name: DBA

on:
  workflow_call:
  workflow_dispatch:

jobs:
  dba:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DBA repository
        uses: actions/checkout@v5
        with:
          repository: "${{ github.repository_owner }}/DBA"
          path: "${{ github.workspace }}/"
          token: "${{ secrets.PAT }}"

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install -r ${{ github.workspace }}/requirements.txt

      - name: Run DBA script
        run: |
          python ${{ github.workspace }}/DBA.py