name: DigitalEksamen-STADS

on:
  workflow_call:
  workflow_dispatch:

jobs:
  digitaleksamen-stads:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout DigitalEksamen-STADS repository
        uses: actions/checkout@v5
        with:
          repository: "${{ github.repository_owner }}/DigitalEksamen-STADS"
          path: "${{ github.workspace }}/"
          token: "${{ secrets.PAT }}"

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install -r ${{ github.workspace }}/requirements.txt

      - name: Run DigitalEksamen-STADS script
        run: |
          python ${{ github.workspace }}/DigitalEksamen-STADS.py