name: GG.deals

on:
  workflow_call:
  workflow_dispatch:

jobs:
  gg-deals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GG.deals repository
        uses: actions/checkout@v5
        with:
          repository: "${{ github.repository_owner }}/gg.deals"
          path: "${{ github.workspace }}/"
          token: "${{ secrets.PAT }}"

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install -r ${{ github.workspace }}/requirements.txt

      - name: Run GG.deals script
        run: |
          python ${{ github.workspace }}/GG.deals.py