name: Hyundai Update

on:
  workflow_call:
  workflow_dispatch:

jobs:
  hyundai-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Hyundai Update repository
        uses: actions/checkout@v5
        with:
          repository: "${{ github.repository_owner }}/Hyundai-Update"
          path: "${{ github.workspace }}/"
          token: "${{ secrets.PAT }}"

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install -r ${{ github.workspace }}/requirements.txt

      - name: Run Hyundai Update script
        run: |
          python ${{ github.workspace }}/hyundai_update.py