name: Instagram Story Downloader

on:
  workflow_call:
  workflow_dispatch:

jobs:
  instagram-story-downloader:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Instagram Story Downloader repository
        uses: actions/checkout@v5
        with:
          repository: "${{ github.repository_owner }}/instagram-story-downloader"
          path: "${{ github.workspace }}/"
          token: "${{ secrets.PAT }}"

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install -r ${{ github.workspace }}/requirements.txt

      - name: Run Instagram Story Downloader script
        run: |
          python ${{ github.workspace }}/instagram_story_downloader.py