name: Merete (Extended Hours)

on:
  workflow_call:
  workflow_dispatch:

jobs:
  merete-eh:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Merete repository
        uses: actions/checkout@v5
        with:
          repository: "${{ github.repository_owner }}/Merete"
          path: "${{ github.workspace }}/"
          token: "${{ secrets.PAT }}"

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install -r ${{ github.workspace }}/requirements.txt

      - name: Run Merete (Extended Hours) script
        run: |
          python ${{ github.workspace }}/Merete-eh.py