name: Simon

on:
  workflow_call:
  workflow_dispatch:

jobs:
  simon:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Simon repository
        uses: actions/checkout@v5
        with:
          repository: "${{ github.repository_owner }}/Simon"
          path: "${{ github.workspace }}/"
          token: "${{ secrets.PAT }}"

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install -r ${{ github.workspace }}/requirements.txt

      - name: Run Simon script
        run: |
          python ${{ github.workspace }}/Simon.py