name: Twitch VOD Finder

on:
  workflow_call:
  workflow_dispatch:

jobs:
  twitch-vod-finder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Twitch VOD Finder repository
        uses: actions/checkout@v5
        with:
          repository: "${{ github.repository_owner }}/twitch-vod-finder"
          path: "${{ github.workspace }}/"
          token: "${{ secrets.PAT }}"

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          pip install -r ${{ github.workspace }}/requirements.txt

      - name: Run Twitch VOD Finder script
        run: |
          python ${{ github.workspace }}/twitch_vod_finder.py